# Generated by Django 5.1.1 on 2026-05-25 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('kode_awal', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('keterangan', models.TextField()),
                ('jumlah', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('karyawan', 'Karyawan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('kode_barang', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batas_minimal', models.IntegerField(default=15)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kategoribarang')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaksipenjualan')),
            ],
        ),
        migrations.AddField(
            model_name='transaksipenjualan',
            name='kasir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user'),
        ),
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('alasan', models.CharField(choices=[('rusak', 'Barang Rusak'), ('expired', 'Expired'), ('salah_kirim', 'Salah Kirim'), ('lainnya', 'Lainnya')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_retur', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('status_2', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('datang', 'Barang Datang'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('tanggal_pesan', models.DateField(auto_now_add=True)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('jumlah_datang', models.IntegerField(blank=True, null=True)),
                ('jumlah_rusak', models.IntegerField(blank=True, default=0, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
    ]
