# Generated by Django 5.1.1 on 2026-05-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kode_barang',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
